__all__ = ['browseroute', 'frontpage', 'getterroutes', 'hintroutes', 'inforoutes', 'lexicalroutes', 'searchroute',
           'selectionroutes', 'textandindexroutes', 'websocketroutes', 'resetroutes', 'cssroutes', 'authenticationroutes']

"""
what can be found where: [routes/ $ grep "^@" *.py]

    browseroute.py:@hipparchia.route('/browse/<locus>')
    cssroutes.py:@hipparchia.route('/css/<cssrequest>', methods=['GET'])
    frontpage.py:@hipparchia.route('/')
    frontpage.py:@hipparchia.route('/favicon.ico')
    frontpage.py:@hipparchia.route('/apple-touch-icon-precomposed.png')
    frontpage.py:@hipparchia.route('/loadhelpdata')
    getterroutes.py:@hipparchia.route('/getsessionvariables')
    getterroutes.py:@hipparchia.route('/getcookie/<cookienum>')
    getterroutes.py:@hipparchia.route('/getworksof/<authoruid>')
    getterroutes.py:@hipparchia.route('/getstructure/<locus>')
    getterroutes.py:@hipparchia.route('/getauthorinfo/<authorid>')
    getterroutes.py:@hipparchia.route('/getsearchlistcontents')
    getterroutes.py:@hipparchia.route('/getgenrelistcontents')
    getterroutes.py:@hipparchia.route('/getstoredfigure/<figurename>')
    hintroutes.py:@hipparchia.route('/getauthorhint', methods=['GET'])
    hintroutes.py:@hipparchia.route('/getgenrehint', methods=['GET'])
    hintroutes.py:@hipparchia.route('/getworkgenrehint', methods=['GET'])
    hintroutes.py:@hipparchia.route('/getaulocationhint', methods=['GET'])
    hintroutes.py:@hipparchia.route('/getwkprovenancehint', methods=['GET'])
    hintroutes.py:@hipparchia.route('/getlemmahint', methods=['GET'])
    inforoutes.py:@hipparchia.route('/databasecontents/<dictionarytodisplay>')
    inforoutes.py:@hipparchia.route('/csssamples')
    inforoutes.py:@hipparchia.route('/showsession')
    inforoutes.py:@hipparchia.route('/testroute')
    lexicalroutes.py:@hipparchia.route('/dictsearch/<searchterm>')
    lexicalroutes.py:@hipparchia.route('/parse/<observedword>')
    lexicalroutes.py:@hipparchia.route('/reverselookup/<searchterm>')
    resetroutes.py:@hipparchia.route('/resetsession')
    resetroutes.py:@hipparchia.route('/resetvectors')
    resetroutes.py:@hipparchia.route('/resetvectorimages')
    searchroute.py:@hipparchia.route('/executesearch/<searchid>', methods=['GET'])
    selectionroutes.py:@hipparchia.route('/makeselection', methods=['GET'])
    selectionroutes.py:@hipparchia.route('/setsessionvariable', methods=['GET'])
    selectionroutes.py:@hipparchia.route('/clearselections', methods=['GET'])
    selectionroutes.py:@hipparchia.route('/getselections')
    textandindexroutes.py:@hipparchia.route('/indexto', methods=['GET'])
    textandindexroutes.py:@hipparchia.route('/textof', methods=['GET'])
    websocketroutes.py:@hipparchia.route('/confirm/<searchid>')

"""