# -*- coding: utf-8 -*-
#
# SEARCHING
#

EXTERNALGRABBER = False
EXTERNALBINARYNAME = 'HipparchiaGoDBHelper'
# EXTERNALBINARYNAME = 'HipparchiaRustDBHelper'
EXTERNALBINARYDIR = 'externalbinaries'
GRABBERMODULEDIRECTORY = 'externalmodule'
GRABBERCALLEDVIACLI = True

EXTERNALBINARYKNOWSLOGININFO = False
EXTERNALBINARYFAILTHRESHOLD = 3

#
# VECTORS
#

EXTERNALVECTORHELPER = False

#
# WEBSOCKETS
#

# if "EXTERNALWEBSOCKETS = True", then you need to set the following
# networksettings.py: POLLCONNECTIONTYPE = 'redis'

EXTERNALWEBSOCKETS = False

#
# DEBUGGING
#

EXTERNALCLILOGLEVEL = 0
EXTERNALMODLOGLEVEL = 0
EXTERNALWSSLOGLEVEL = 0
EXTERNAVECTORLOGLEVEL = 0

