# -*- coding: utf-8 -*-
# GOLANGGRABBER = False
# GOLANGLOADING = 'cli'
# # GOLANGLOADING = 'module'
#
# GOLANGCLIBINARYNAME = 'HipparchiaGoDBHelper'
# GOLANGBINARYKNOWSLOGININFO = False
# GOLANGWSFAILTHRESHOLD = 3

#
# SEARCHING
#

EXTERNALGRABBER = False
EXTERNALBINARYNAME = 'HipparchiaGoDBHelper'
EXTERNALBINARYDIR = 'externalbinaries'
GRABBERMODULEDIRECTORY = 'golangmodule'
GRABBERCALLEDVIACLI = True

EXTERNALBINARYKNOWSLOGININFO = False
EXTERNALBINARYFAILTHRESHOLD = 3

EXTERNALVECTORHELPER = False

#
# WEBSOCKETS
#

EXTERNALWEBSOCKETS = False

#
# DEBUGGING
#

EXTERNALCLILOGLEVEL = 0
EXTERNALMODLOGLEVEL = 0
EXTERNALWSSLOGLEVEL = 0
EXTERNAVECTORLOGLEVEL = 0

